name: CHIPS Automation Workflow

on:
  push:
    branches:
      # Push events on master branch
      - master
      # - develop
      # Push events to branches matching refs/heads/releases/10
      # - "releases/**"
  # release:
  #   types:
  #     - created

jobs:
  create-new-branch:
    name: Create new branch

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/} before checkout

      - name: checkout to this branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{secrets.WORKFLOW_TOKEN}}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_github_workflows
          sudo chmod 600 ~/.ssh/id_github_workflows
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_CONFIG" > ~/.ssh/config
        shell: bash
        env:
          SSH_KEY: ${{secrets.WORKFLOW_SSH_KEY}}
          KNOWN_HOSTS: ${{secrets.WORKFLOW_SSH_KNOWN_HOSTS}}
          SSH_CONFIG: ${{secrets.WORKFLOW_SSH_CONFIG}}

      - name: Create branch
        shell: bash
        env:
          CURRENT_USER: ${{ github.actor }}
        run: |
          ./.github/workflows/branch-creation.sh
